export const appAssets = {
  splashBackground: require('./arvexa-launch-backdrop.png'),
  logo: require('./arvexa-bowrix-brand-mark.png'),
  conditionsHero: require('./arvexa-range-weather-hero.png'),
  bowSetupHero: require('./arvexa-tuning-workbench-hero.png'),
  scoreAverageHero: require('./arvexa-grouping-analytics-hero.png'),
  arrowSpeedHero: require('./arvexa-velocity-lab-hero.png'),
  onboardingMasterArchery: require('./arvexa-welcome-mastery.png'),
  onboardingFineTuneBow: require('./arvexa-welcome-tuning.png'),
  onboardingTrackEveryShot: require('./arvexa-welcome-tracking.png'),
  onboardingLearnAndImprove: require('./arvexa-welcome-learning.png'),
  bowRecurve: require('./arvexa-bow-recurve-profile.png'),
  bowCompound: require('./arvexa-bow-compound-profile.png'),
  bowLongbow: require('./arvexa-bow-longbow-profile.png'),
  bowTraditional: require('./arvexa-bow-traditional-profile.png'),
  bowOlympicRecurve: require('./arvexa-bow-olympic-profile.png'),
  bowHunting: require('./arvexa-bow-hunting-profile.png'),
  bowHorse: require('./arvexa-bow-horsebow-profile.png'),
  bowFlatbow: require('./arvexa-bow-flatbow-profile.png'),
};
