export const appAssets = {
  splashBackground: require('./splash-background.png'),
  logo: require('./arvexa-bowrix-logo.png'),
  conditionsHero: require('./shooting-conditions-hero.png'),
  bowSetupHero: require('./bow-setup-hero.png'),
  scoreAverageHero: require('./score-average-hero.png'),
  arrowSpeedHero: require('./arrow-speed-hero.png'),
  onboardingMasterArchery: require('./onboarding-master-archery.png'),
  onboardingFineTuneBow: require('./onboarding-fine-tune-bow.png'),
  onboardingTrackEveryShot: require('./onboarding-track-every-shot.png'),
  onboardingLearnAndImprove: require('./onboarding-learn-and-improve.png'),
  bowRecurve: require('./bow-recurve.png'),
  bowCompound: require('./bow-compound.png'),
  bowLongbow: require('./bow-longbow.png'),
  bowTraditional: require('./bow-traditional.png'),
  bowOlympicRecurve: require('./bow-olympic-recurve.png'),
  bowHunting: require('./bow-hunting.png'),
  bowHorse: require('./bow-horse.png'),
  bowFlatbow: require('./bow-flatbow.png'),
};
